-- Divides two numbers

DELIMITER $$
CREATE FUNCTION SafeDiv (a INT, b INT)
RETURNS FLOAT
DETERMINISTIC
BEGIN
IF (b = 0)
	THEN
	RETURN 0;
ELSE
	RETURN (CAST(a AS DECIMAL(30, 20)) / b AS output FROM dual);
	END IF;
END $$
DELIMITER ;
