-- Divides two numbers

DELIMITER $$
CREATE FUNCTION SafeDiv (a INT, b INT)
RETURNS DEC(32, 24)
DETERMINISTIC
BEGIN
	IF (b = 0)
		THEN
		RETURN 0;
	ELSE
		SET @c DECIMAL(32, 24) = (CAST(a AS DEC(32, 24)) / (b + 0));
		RETURN c;
	END IF;
END $$
DELIMITER $$
